name: Merge PR with template release changes

on:
  workflow_dispatch:

jobs:
  disable_protections:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Enable merge
        shell: bash
        run: |
          gh repo edit --enable-merge-commit=true
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Allow bypass protection by admings
        uses: octokit/request-action@v2.1.7
        with:
          route: DELETE /repos/${{ github.repository }}/branches/main/protection/enforce_admins
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  merge_pr_with_template_release_changes:
    runs-on: ubuntu-latest
    needs: disable_protections
    outputs:
      TEMPLATE_LATEST_RELEASE: ${{ steps.template_latest_release.outputs.value }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}        
      - name: Search Pull Request
        id: search_pr
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RESULT=$(gh pr list --json number,title,headRefName -S 'chore: merge ${{ vars.TEMPLATE_REPO }}')
          echo "result=$RESULT" >> $GITHUB_OUTPUT

          NUMBER_OF_PR_FOUND=$(echo $RESULT | jq '. | length')
          echo "count=$NUMBER_OF_PR_FOUND" >> $GITHUB_OUTPUT
      - name: Cancel Workflow if more than one PR found or no PR found
        uses: potiuk/cancel-workflow-runs@v4_7
        if: ${{ steps.search_pr.outputs.count != 1}}
        with:
          cancelMode: self
          selfPreservation: false
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge the PR
        shell: bash
        run: |
          gh pr merge ${{ fromJSON(steps.search_pr.outputs.result)[0].number }} -d -m -t "${{ fromJSON(steps.search_pr.outputs.result)[0].title }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Extract template latest release name
        id: template_latest_release
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          IFS='_'
          read -a strarr <<< $(gh pr view ${{ fromJSON(steps.search_pr.outputs.result)[0].number }} --json headRefName --jq '.headRefName')
          IFS=' '
          TEMPLATE_LATEST_RELEASE=${strarr[-1]}
          echo "value=$TEMPLATE_LATEST_RELEASE" >> $GITHUB_OUTPUT
  update_variables:
    runs-on: ubuntu-latest
    needs: merge_pr_with_template_release_changes
    if: needs.merge_pr_with_template_release_changes.result == 'success'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - shell: bash
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/actions/variables/UPDATED_TO_TEMPLATE_RELEASE -f name='UPDATED_TO_TEMPLATE_RELEASE' -f value='${{ needs.merge_pr_with_template_release_changes.outputs.TEMPLATE_LATEST_RELEASE }}'
  restore_protections:
    runs-on: ubuntu-latest
    needs: [disable_protections, merge_pr_with_template_release_changes]
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - shell: bash
        env:
          GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        run: |
          # Disable merge 
          gh repo edit --enable-merge-commit=false
          # Disable allow bypass protection rules by admins
          gh api --method POST -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /repos/${{ github.repository }}/branches/main/protection/enforce_admins